LL-2D-DGR: FluidParams Module Reference
FluidParams Module Reference
Variables
REAL(KIND=DBL) beta
REAL(KIND=DBL) beta4
REAL(KIND=DBL), dimension(:,:),
allocatable bubbles
REAL(KIND=DBL), dimension(1:11) Convergence
REAL(KIND=DBL) eps
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoSq_f
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoX
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoX_f
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoXX_f
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoXY_f
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoY
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoY_f
REAL(KIND=DBL), dimension(:,:),
allocatable gradRhoYY_f
REAL(KIND=DBL), dimension(:,:),
allocatable GX
REAL(KIND=DBL), dimension(:,:),
allocatable GY
REAL(KIND=DBL) IntWidth
REAL(KIND=DBL) kappa
REAL(KIND=DBL) kappa_6
REAL(KIND=DBL) kappaEf
REAL(KIND=DBL) kappaG
INTEGER nBubbles
REAL(KIND=DBL), dimension(:,:),
allocatable p
REAL(KIND=DBL), dimension(:,:),
allocatable p_f
REAL(KIND=DBL) pConv
REAL(KIND=DBL), dimension(:,:),
allocatable psi
REAL(KIND=DBL), dimension(:,:),
allocatable psi_f
REAL(KIND=DBL), dimension(:,:),
allocatable rho
REAL(KIND=DBL), dimension(:,:),
allocatable rho_f
REAL(KIND=DBL) rhoH
REAL(KIND=DBL) rhoL
REAL(KIND=DBL) rhoStar
REAL(KIND=DBL) sigma
REAL(KIND=DBL) tauH
REAL(KIND=DBL) tauL
REAL(KIND=DBL) tauRhoStar
REAL(KIND=DBL), dimension(:,:,:),
allocatable u
REAL(KIND=DBL), dimension(:,:,:),
allocatable u_f
Variable Documentation
REAL(KIND = DBL) FluidParams::beta
Definition at line 75 of file common.f.
Referenced by Init(), and Parameters().
REAL(KIND = DBL) FluidParams::beta4
Definition at line 75 of file common.f.
Referenced by HydrodynamicsF(), and Parameters().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::bubbles
Definition at line 72 of file common.f.
Referenced by FinalDump(), Init(), Parameters(), and Stats().
REAL(KIND = DBL),dimension(1:11) FluidParams::Convergence
Definition at line 73 of file common.f.
Referenced by Stats().
REAL(KIND = DBL) FluidParams::eps
Definition at line 77 of file common.f.
Referenced by Init(), main(), and Stats().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoSq_f
Definition at line 88 of file common.f.
Referenced by Init(), MemAlloc(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoX
Definition at line 85 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoX_f
Definition at line 86 of file common.f.
Referenced by HydrodynamicsF(), Init(), MemAlloc(), PostStreamF(), PreStreamF(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoXX_f
Definition at line 87 of file common.f.
Referenced by Init(), MemAlloc(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoXY_f
Definition at line 87 of file common.f.
Referenced by Init(), MemAlloc(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoY
Definition at line 85 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoY_f
Definition at line 86 of file common.f.
Referenced by HydrodynamicsF(), Init(), MemAlloc(), PostStreamF(), PreStreamF(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::gradRhoYY_f
Definition at line 88 of file common.f.
Referenced by Init(), MemAlloc(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::GX
Definition at line 85 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), and UpdateG().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::GY
Definition at line 85 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), and UpdateG().
REAL(KIND = DBL) FluidParams::IntWidth
Definition at line 74 of file common.f.
Referenced by FinalDump(), Init(), Parameters(), and Stats().
REAL(KIND = DBL) FluidParams::kappa
Definition at line 75 of file common.f.
Referenced by Parameters().
REAL(KIND = DBL) FluidParams::kappa_6
Definition at line 75 of file common.f.
Referenced by HydrodynamicsF(), Init(), and Parameters().
REAL(KIND = DBL) FluidParams::kappaEf
Definition at line 75 of file common.f.
Referenced by Init(), Parameters(), and UpdateG().
REAL(KIND = DBL) FluidParams::kappaG
Definition at line 75 of file common.f.
Referenced by Parameters().
INTEGER FluidParams::nBubbles
Definition at line 71 of file common.f.
Referenced by Init(), and Parameters().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::p
Definition at line 80 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), UpdateF(), and VtkPlane().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::p_f
Definition at line 80 of file common.f.
Referenced by FinalDump(), Init(), MemAlloc(), Stats(), and UpdateF().
REAL(KIND = DBL) FluidParams::pConv
Definition at line 77 of file common.f.
Referenced by main(), and Parameters().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::psi
Definition at line 84 of file common.f.
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::psi_f
Definition at line 84 of file common.f.
Referenced by HydrodynamicsF(), Init(), MemAlloc(), PostStreamF(), and PreStreamF().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::rho
Definition at line 84 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), UpdateG(), and VtkPlane().
REAL(KIND = DBL),dimension(:,:),allocatable FluidParams::rho_f
Definition at line 84 of file common.f.
Referenced by FinalDump(), HydrodynamicsF(), Init(), MemAlloc(), PostStreamF(), PreStreamF(), Stats(), and UpdateG().
REAL(KIND = DBL) FluidParams::rhoH
Definition at line 76 of file common.f.
Referenced by FinalDump(), HydrodynamicsF(), Init(), and Parameters().
REAL(KIND = DBL) FluidParams::rhoL
Definition at line 76 of file common.f.
Referenced by FinalDump(), HydrodynamicsF(), Init(), Parameters(), PostStreamF(), PostStreamG(), PreStreamF(), and PreStreamG().
REAL(KIND = DBL) FluidParams::rhoStar
Definition at line 76 of file common.f.
Referenced by FinalDump(), HydrodynamicsF(), Init(), and Stats().
REAL(KIND = DBL) FluidParams::sigma
Definition at line 74 of file common.f.
Referenced by FinalDump(), Parameters(), and Stats().
REAL(KIND = DBL) FluidParams::tauH
Definition at line 76 of file common.f.
Referenced by FinalDump(), and Parameters().
REAL(KIND = DBL) FluidParams::tauL
Definition at line 76 of file common.f.
Referenced by FinalDump(), Parameters(), PostStreamF(), PostStreamG(), PreStreamF(), and PreStreamG().
REAL(KIND = DBL) FluidParams::tauRhoStar
Definition at line 76 of file common.f.
Referenced by Parameters(), PostStreamF(), PostStreamG(), PreStreamF(), and PreStreamG().
REAL(KIND = DBL),dimension(:,:,:),allocatable FluidParams::u
Definition at line 81 of file common.f.
Referenced by HydrodynamicsG(), Init(), MemAlloc(), PostStreamG(), PreStreamG(), UpdateF(), and VtkPlane().
REAL(KIND = DBL),dimension(:,:,:),allocatable FluidParams::u_f
Definition at line 81 of file common.f.
Referenced by FinalDump(), Init(), MemAlloc(), PostStreamF(), PreStreamF(), Stats(), and UpdateF().