LL-2D-STD-MPI: src/parallel/ll-src/vtkplane.f File Reference
src/parallel/ll-src/vtkplane.f File Reference
Detailed Description
Save order parameter, pressure, and velocity data in VTK format for the D2Q9 Lee-Lin multiphase LBM. Filenames are 'DATA_XXXXXXX.VTK' where XXXXXXX is the time step. These files are understood by Paraview.
Definition in file vtkplane.f.
Functions/Subroutines
CHARACTER(12) filer ()
subroutine VtkPlane
Function Documentation
CHARACTER(12) filer ()
Set vtk file name as a function of processor number and time step.
Definition at line 107 of file vtkplane.f.
References MPIParams::vproc.
Referenced by VtkPlane().
subroutine VtkPlane ()
Definition at line 29 of file vtkplane.f.
References filer(), MemAlloc(), Domain::NX, Domain::NY, FluidParams::p, FluidParams::rho, FluidParams::u, Domain::xl, Domain::xu, Domain::yl, and Domain::yu.
Referenced by Init(), and main().