ZSC-2D-DGR: src/serial/zsc-dgr-src/main.f File Reference
src/serial/zsc-dgr-src/main.f File Reference
Detailed Description
Driver for the dual grid implementation of the Zheng-Shu-Chew multiphase LBM using D2Q5/D2Q9 discretization and periodic boundary conditions. For details:
Journal of Computational Physics 218: 353-371, 2006.
Serial Implementation. Convergence test and post-processing functions designed for single drop/bubble cases.
In this dual grid implementation the order parameter grid is twice larger than the coarser momentum grid. This provides improved numerical differentials at the interface and leads to better mass conservation and greater stability. All differential terms are calculated in the order parameter grid and then copied over to the momentum grid (the grids overlap). The velocity and pressure are calculated in the momentum grid and interpolated in the order parameter grid. Two collision-stream steps are are taken in the order parameter grid for every step taken in the momentum grid to ensure synchronization.
The average velocity, mass conservation factor, effective radius of the drop, pressure difference between the inside and the outside of the drop and the error with respect to the analytical value given by Laplace's equation are written to file "stats.out"
Definition in file main.f.
Functions/Subroutines
program main
Function Documentation
program main ()
Definition at line 48 of file main.f.
References CollisionF(), CollisionG(), Differentials(), FluidParams::eps, FinalDump(), Init(), Domain::iStep, Domain::MaxStep, MemAlloc(), Domain::now, Domain::nxt, Parameters(), FluidParams::pConv, Domain::RelaxStep, Stats(), Stream(), Domain::tDump, Domain::tStat, Update(), and VtkPlane().