LL-2D-DGR-MPI: src/parallel/ll-dgr-src/memalloc.f File Reference
src/parallel/ll-dgr-src/memalloc.f File Reference
Detailed Description
If FLAG is 1 then memory is allocated for the following common arrays:
p, p_f (pressure)
u, u_f (velocity)
rho, rho_f (density)
psi_f (chemical potential)
ni, ni_f (near neighbors)
f, fbar (order parameter distribution function)
g, gbar (momentum distribution function)
GX, GY (components of the interfacial force - potential formulation)
gradRhoX, gradRhoX_f (x component of the gradient of the density)
gradRhoY, gradRhoY_f (y component of the gradient of the density)
gradRhoSq_f (gradient of the density squared)
gradRhoXX_f (x component of the gradient of the density squared)
gradRhoXY_f (product of the x and y components of the density gradient)
gradRhoYY_f (y component of the gradient of the density squared)
and the buffer arrays required by the parallel dual grid D2Q9 Lee-Lin multiphase LBM. Arrays are deallocated when FLAG is different from one.
Definition in file memalloc.f.
Functions/Subroutines
subroutine MemAlloc (FLAG)
Function Documentation
subroutine MemAlloc (INTEGER,intent(in) FLAG)
Definition at line 45 of file memalloc.f.
References LBMParams::f, MPIParams::f_east_rcv, MPIParams::f_east_snd, MPIParams::f_north_rcv, MPIParams::f_north_snd, MPIParams::f_south_rcv, MPIParams::f_south_snd, MPIParams::f_west_rcv, MPIParams::f_west_snd, LBMParams::fbar, LBMParams::fdim, LBMParams::g, MPIParams::g_east_rcv, MPIParams::g_east_snd, MPIParams::g_north_rcv, MPIParams::g_north_snd, MPIParams::g_south_rcv, MPIParams::g_south_snd, MPIParams::g_west_rcv, MPIParams::g_west_snd, LBMParams::gbar, LBMParams::gdim, FluidParams::gradRhoSq_f, FluidParams::gradRhoX, FluidParams::gradRhoX_f, FluidParams::gradRhoXX_f, FluidParams::gradRhoXY_f, FluidParams::gradRhoY, FluidParams::gradRhoY_f, FluidParams::gradRhoYY_f, FluidParams::GX, FluidParams::GY, MPIParams::hydro_east_rcv, MPIParams::hydro_east_snd, MPIParams::hydro_north_rcv, MPIParams::hydro_north_snd, MPIParams::hydro_south_rcv, MPIParams::hydro_south_snd, MPIParams::hydro_west_rcv, MPIParams::hydro_west_snd, Domain::ni, Domain::ni_f, FluidParams::p, FluidParams::p_f, FluidParams::psi_f, FluidParams::rho, MPIParams::rho_east_rcv, MPIParams::rho_east_snd, FluidParams::rho_f, MPIParams::rho_north_rcv, MPIParams::rho_north_snd, MPIParams::rho_south_rcv, MPIParams::rho_south_snd, MPIParams::rho_west_rcv, MPIParams::rho_west_snd, MPIParams::rhoG_east_rcv, MPIParams::rhoG_east_snd, MPIParams::rhoG_north_rcv, MPIParams::rhoG_north_snd, MPIParams::rhoG_south_rcv, MPIParams::rhoG_south_snd, MPIParams::rhoG_west_rcv, MPIParams::rhoG_west_snd, FluidParams::u, FluidParams::u_f, Domain::xl, Domain::xl_f, Domain::xlg, Domain::xlg2, Domain::xlg2_f, Domain::xlg3_f, Domain::xlg_f, MPIParams::xsize, MPIParams::xsize2, MPIParams::xsize3, MPIParams::xsize3_f, MPIParams::xsize_f, Domain::xu, Domain::xu_f, Domain::xug, Domain::xug2, Domain::xug2_f, Domain::xug3_f, Domain::xug_f, Domain::yl, Domain::yl_f, Domain::ylg, Domain::ylg2, Domain::ylg2_f, Domain::ylg3_f, Domain::ylg_f, MPIParams::ysize, MPIParams::ysize2, MPIParams::ysize3, MPIParams::ysize3_f, MPIParams::ysize_f, Domain::yu, Domain::yu_f, Domain::yug, Domain::yug2, Domain::yug2_f, Domain::yug3_f, and Domain::yug_f.
Referenced by FinalDump(), main(), Stats(), and VtkPlane().