ZSC-3D-STD-MPI: src/parallel/zsc-3d-src/init.f File Reference
src/parallel/zsc-3d-src/init.f File Reference
Detailed Description
Initialization step for the parallel D3Q7/D3Q19 Zheng-Shu-Chew multiphase LBM. Smeared interface initialized using equilibrium order parameter function for each drop defined in the input (in the range [R-IntWidth,R+IntWidth]). The distribution functions f and g are initialized to their equilibrium values for zero velocity.
Definition in file init.f.
Functions/Subroutines
subroutine Init
Function Documentation
subroutine Init ()
Definition at line 32 of file init.f.
References FluidParams::alpha4, MPIParams::bot, FluidParams::bubbles, MPIParams::east, LBMParams::Eg0, LBMParams::Eg1, LBMParams::Eg2, FluidParams::eps, LBMParams::f, MPIParams::f_bot_rcv, MPIParams::f_bot_snd, MPIParams::f_east_rcv, MPIParams::f_east_snd, MPIParams::f_north_rcv, MPIParams::f_north_snd, MPIParams::f_south_rcv, MPIParams::f_south_snd, MPIParams::f_top_rcv, MPIParams::f_top_snd, MPIParams::f_west_rcv, MPIParams::f_west_snd, LBMParams::g, FluidParams::Gamma, FluidParams::IntWidth, Domain::inv6, Domain::iStep, FluidParams::kappa, MPIParams::MPI_COMM_VGRID, FluidParams::nBubbles, Domain::ni, MPIParams::north, Domain::now, Domain::NPX, Domain::NPZ, Domain::NX, Domain::nxt, Domain::NY, Domain::NZ, FluidParams::phi, FluidParams::phiStar, FluidParams::rhoH, FluidParams::rhoL, MPIParams::south, Stats(), MPIParams::TAG1, MPIParams::TAG2, Domain::tCall, MPIParams::top, VtkDump(), MPIParams::west, Domain::xjump, Domain::xl, Domain::xlg, Domain::xmax, Domain::xmin, Domain::xsize, Domain::xu, Domain::xug, Domain::yl, Domain::ylg, Domain::ymax, Domain::ymin, Domain::ysize, Domain::yu, Domain::yug, Domain::zl, Domain::zlg, Domain::zmax, Domain::zmin, Domain::zsize, Domain::zu, and Domain::zug.
Referenced by main().