ZSC-3D-STD-MPI: LBMParams Module Reference
LBMParams Module Reference
Variables
REAL(KIND=DBL), parameter Cs = 0.57735026918962576451D0
REAL(KIND=DBL), parameter Cs_sq = 0.33333333333333333333D0
REAL(KIND=DBL), parameter Eg0 = 0.33333333333333333333D0
REAL(KIND=DBL), parameter Eg0C = 1.00000000000000000000D0
REAL(KIND=DBL) Eg0n
REAL(KIND=DBL), parameter Eg1 = 0.05555555555555555556D0
REAL(KIND=DBL), parameter Eg1C = 0.16666666666666666667D0
REAL(KIND=DBL) Eg1n
REAL(KIND=DBL), parameter Eg2 = 0.02777777777777777778D0
REAL(KIND=DBL), parameter Eg2C = 0.08333333333333333333D0
REAL(KIND=DBL) Eg2n
REAL(KIND=DBL) EgC0n
REAL(KIND=DBL) EgC1n
REAL(KIND=DBL) EgC2n
REAL(KIND=DBL), dimension(:,:,:,:,:),
allocatable f
INTEGER, parameter fdim = 6
REAL(KIND=DBL), dimension(:,:,:,:,:),
allocatable g
INTEGER, parameter gdim = 18
REAL(KIND=DBL), parameter invCs_sq = 3.00000000000000000000D0
REAL(KIND=DBL) w
Variable Documentation
REAL(KIND = DBL),parameter LBMParams::Cs = 0.57735026918962576451D0
Definition at line 110 of file common.f.
REAL(KIND = DBL),parameter LBMParams::Cs_sq = 0.33333333333333333333D0
Definition at line 111 of file common.f.
Referenced by RelaxStats(), and VtkDump().
REAL(KIND = DBL),parameter LBMParams::Eg0 = 0.33333333333333333333D0
Definition at line 115 of file common.f.
Referenced by Init(), and Parameters().
REAL(KIND = DBL),parameter LBMParams::Eg0C = 1.00000000000000000000D0
Definition at line 120 of file common.f.
Referenced by Parameters().
REAL(KIND = DBL) LBMParams::Eg0n
Definition at line 123 of file common.f.
Referenced by Collision(), CollisionRelax(), and Parameters().
REAL(KIND = DBL),parameter LBMParams::Eg1 = 0.05555555555555555556D0
Definition at line 116 of file common.f.
Referenced by Init(), and Parameters().
REAL(KIND = DBL),parameter LBMParams::Eg1C = 0.16666666666666666667D0
Definition at line 121 of file common.f.
Referenced by Parameters().
REAL(KIND = DBL) LBMParams::Eg1n
Definition at line 123 of file common.f.
Referenced by Collision(), CollisionRelax(), and Parameters().
REAL(KIND = DBL),parameter LBMParams::Eg2 = 0.02777777777777777778D0
Definition at line 117 of file common.f.
Referenced by Init(), and Parameters().
REAL(KIND = DBL),parameter LBMParams::Eg2C = 0.08333333333333333333D0
Definition at line 122 of file common.f.
Referenced by Parameters().
REAL(KIND = DBL) LBMParams::Eg2n
Definition at line 123 of file common.f.
Referenced by Collision(), CollisionRelax(), and Parameters().
REAL(KIND = DBL) LBMParams::EgC0n
Definition at line 123 of file common.f.
Referenced by Collision(), CollisionRelax(), and Parameters().
REAL(KIND = DBL) LBMParams::EgC1n
Definition at line 123 of file common.f.
Referenced by Collision(), CollisionRelax(), and Parameters().
REAL(KIND = DBL) LBMParams::EgC2n
Definition at line 123 of file common.f.
Referenced by Collision(), CollisionRelax(), and Parameters().
REAL(KIND = DBL),dimension(:,:,:,:,:),allocatable LBMParams::f
Definition at line 107 of file common.f.
Referenced by Collision(), CollisionRelax(), Init(), MemAlloc(), PostCollision(), PostStream(), and Stream().
INTEGER,parameter LBMParams::fdim = 6
Definition at line 103 of file common.f.
Referenced by MemAlloc().
REAL(KIND = DBL),dimension(:,:,:,:,:),allocatable LBMParams::g
Definition at line 107 of file common.f.
Referenced by Collision(), CollisionRelax(), FinalDump(), Init(), MemAlloc(), PostCollision(), PostStream(), RelaxStats(), Stats(), and VtkDump().
INTEGER,parameter LBMParams::gdim = 18
Definition at line 104 of file common.f.
Referenced by MemAlloc().
REAL(KIND = DBL),parameter LBMParams::invCs_sq = 3.00000000000000000000D0
Definition at line 112 of file common.f.
Referenced by Collision(), CollisionRelax(), and FinalDump().
REAL(KIND = DBL) LBMParams::w
Definition at line 123 of file common.f.