ZSC-3D-STD-MPI: MPIParams Module Reference
MPIParams Module Reference
Detailed Description
Parameters:
nprocs : total number of processors
proc : processor ID
vproc : processor ID in virtual grid
mpi_dim : virtual grid partition scheme (1->stripes, 2->boxes, 3->cubes)
Variables
INTEGER be
INTEGER bn
INTEGER bot
INTEGER bs
INTEGER bw
INTEGER east
REAL(KIND=DBL), dimension(:),
allocatable f_bot_rcv
REAL(KIND=DBL), dimension(:),
allocatable f_bot_snd
REAL(KIND=DBL), dimension(:),
allocatable f_east_rcv
REAL(KIND=DBL), dimension(:),
allocatable f_east_snd
REAL(KIND=DBL), dimension(:),
allocatable f_north_rcv
REAL(KIND=DBL), dimension(:),
allocatable f_north_snd
REAL(KIND=DBL), dimension(:),
allocatable f_south_rcv
REAL(KIND=DBL), dimension(:),
allocatable f_south_snd
REAL(KIND=DBL), dimension(:),
allocatable f_top_rcv
REAL(KIND=DBL), dimension(:),
allocatable f_top_snd
REAL(KIND=DBL), dimension(:),
allocatable f_west_rcv
REAL(KIND=DBL), dimension(:),
allocatable f_west_snd
REAL(KIND=DBL), dimension(:),
allocatable g_be_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_be_snd
REAL(KIND=DBL), dimension(:),
allocatable g_bn_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_bn_snd
REAL(KIND=DBL), dimension(:),
allocatable g_bot_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_bot_snd
REAL(KIND=DBL), dimension(:),
allocatable g_bs_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_bs_snd
REAL(KIND=DBL), dimension(:),
allocatable g_bw_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_bw_snd
REAL(KIND=DBL), dimension(:),
allocatable g_east_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_east_snd
REAL(KIND=DBL), dimension(:),
allocatable g_ne_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_ne_snd
REAL(KIND=DBL), dimension(:),
allocatable g_north_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_north_snd
REAL(KIND=DBL), dimension(:),
allocatable g_nw_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_nw_snd
REAL(KIND=DBL), dimension(:),
allocatable g_se_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_se_snd
REAL(KIND=DBL), dimension(:),
allocatable g_south_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_south_snd
REAL(KIND=DBL), dimension(:),
allocatable g_sw_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_sw_snd
REAL(KIND=DBL), dimension(:),
allocatable g_te_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_te_snd
REAL(KIND=DBL), dimension(:),
allocatable g_tn_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_tn_snd
REAL(KIND=DBL), dimension(:),
allocatable g_top_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_top_snd
REAL(KIND=DBL), dimension(:),
allocatable g_ts_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_ts_snd
REAL(KIND=DBL), dimension(:),
allocatable g_tw_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_tw_snd
REAL(KIND=DBL), dimension(:),
allocatable g_west_rcv
REAL(KIND=DBL), dimension(:),
allocatable g_west_snd
INTEGER, parameter master = 0
INTEGER MPI_COMM_VGRID
INTEGER, parameter mpi_dim = 3
INTEGER mpi_xdim
INTEGER mpi_ydim
INTEGER mpi_zdim
INTEGER ne
INTEGER north
INTEGER nprocs
INTEGER nw
REAL(KIND=DBL), dimension(:),
allocatable phi_be_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_be_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_bn_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_bn_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_bot_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_bot_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_bs_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_bs_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_bw_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_bw_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_east_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_east_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_ne_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_ne_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_north_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_north_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_nw_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_nw_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_se_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_se_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_south_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_south_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_sw_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_sw_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_te_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_te_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_tn_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_tn_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_top_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_top_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_ts_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_ts_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_tw_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_tw_snd
REAL(KIND=DBL), dimension(:),
allocatable phi_west_rcv
REAL(KIND=DBL), dimension(:),
allocatable phi_west_snd
INTEGER proc
INTEGER se
INTEGER south
INTEGER sw
INTEGER, parameter TAG1 = 1
INTEGER, parameter TAG2 = 2
INTEGER, parameter TAG3 = 3
INTEGER, parameter TAG4 = 4
INTEGER te
INTEGER tn
INTEGER top
INTEGER ts
INTEGER tw
INTEGER vproc
INTEGER west
Variable Documentation
INTEGER MPIParams::be
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::bn
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::bot
Definition at line 141 of file common.f.
Referenced by Init(), PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::bs
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::bw
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::east
Definition at line 141 of file common.f.
Referenced by Init(), PostCollision(), PostStream(), and VGrid().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_bot_rcv
Definition at line 165 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_bot_snd
Definition at line 164 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_east_rcv
Definition at line 149 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_east_snd
Definition at line 148 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_north_rcv
Definition at line 157 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_north_snd
Definition at line 156 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_south_rcv
Definition at line 157 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_south_snd
Definition at line 156 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_top_rcv
Definition at line 165 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_top_snd
Definition at line 164 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_west_rcv
Definition at line 149 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::f_west_snd
Definition at line 148 of file common.f.
Referenced by Init(), MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_be_rcv
Definition at line 183 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_be_snd
Definition at line 183 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bn_rcv
Definition at line 173 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bn_snd
Definition at line 173 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bot_rcv
Definition at line 167 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bot_snd
Definition at line 166 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bs_rcv
Definition at line 175 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bs_snd
Definition at line 175 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bw_rcv
Definition at line 185 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_bw_snd
Definition at line 185 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_east_rcv
Definition at line 151 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_east_snd
Definition at line 150 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_ne_rcv
Definition at line 192 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_ne_snd
Definition at line 192 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_north_rcv
Definition at line 159 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_north_snd
Definition at line 158 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_nw_rcv
Definition at line 194 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_nw_snd
Definition at line 194 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_se_rcv
Definition at line 193 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_se_snd
Definition at line 193 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_south_rcv
Definition at line 159 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_south_snd
Definition at line 158 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_sw_rcv
Definition at line 195 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_sw_snd
Definition at line 195 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_te_rcv
Definition at line 182 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_te_snd
Definition at line 182 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_tn_rcv
Definition at line 172 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_tn_snd
Definition at line 172 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_top_rcv
Definition at line 167 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_top_snd
Definition at line 166 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_ts_rcv
Definition at line 174 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_ts_snd
Definition at line 174 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_tw_rcv
Definition at line 184 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_tw_snd
Definition at line 184 of file common.f.
Referenced by MemAlloc(), and PostCollision().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_west_rcv
Definition at line 151 of file common.f.
Referenced by MemAlloc(), PostCollision(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::g_west_snd
Definition at line 150 of file common.f.
Referenced by MemAlloc(), and PostCollision().
INTEGER,parameter MPIParams::master = 0
Definition at line 143 of file common.f.
Referenced by FinalDump(), Parameters(), RelaxStats(), and Stats().
INTEGER MPIParams::MPI_COMM_VGRID
Definition at line 139 of file common.f.
Referenced by FinalDump(), Init(), PostCollision(), PostStream(), RelaxStats(), Stats(), and VGrid().
INTEGER,parameter MPIParams::mpi_dim = 3
Definition at line 144 of file common.f.
Referenced by VGrid().
INTEGER MPIParams::mpi_xdim
Definition at line 140 of file common.f.
Referenced by FinalDump(), Parameters(), and VGrid().
INTEGER MPIParams::mpi_ydim
Definition at line 140 of file common.f.
Referenced by FinalDump(), Parameters(), and VGrid().
INTEGER MPIParams::mpi_zdim
Definition at line 140 of file common.f.
Referenced by FinalDump(), Parameters(), and VGrid().
INTEGER MPIParams::ne
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::north
Definition at line 141 of file common.f.
Referenced by Init(), PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::nprocs
Definition at line 139 of file common.f.
Referenced by main().
INTEGER MPIParams::nw
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_be_rcv
Definition at line 187 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_be_snd
Definition at line 187 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bn_rcv
Definition at line 177 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bn_snd
Definition at line 177 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bot_rcv
Definition at line 169 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bot_snd
Definition at line 168 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bs_rcv
Definition at line 179 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bs_snd
Definition at line 179 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bw_rcv
Definition at line 189 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_bw_snd
Definition at line 189 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_east_rcv
Definition at line 153 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_east_snd
Definition at line 152 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_ne_rcv
Definition at line 196 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_ne_snd
Definition at line 196 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_north_rcv
Definition at line 161 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_north_snd
Definition at line 160 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_nw_rcv
Definition at line 198 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_nw_snd
Definition at line 198 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_se_rcv
Definition at line 197 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_se_snd
Definition at line 197 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_south_rcv
Definition at line 161 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_south_snd
Definition at line 160 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_sw_rcv
Definition at line 199 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_sw_snd
Definition at line 199 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_te_rcv
Definition at line 186 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_te_snd
Definition at line 186 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_tn_rcv
Definition at line 176 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_tn_snd
Definition at line 176 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_top_rcv
Definition at line 169 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_top_snd
Definition at line 168 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_ts_rcv
Definition at line 178 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_ts_snd
Definition at line 178 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_tw_rcv
Definition at line 188 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_tw_snd
Definition at line 188 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_west_rcv
Definition at line 153 of file common.f.
Referenced by MemAlloc(), and PostStream().
REAL(KIND = DBL),dimension(:),allocatable MPIParams::phi_west_snd
Definition at line 152 of file common.f.
Referenced by MemAlloc(), and PostStream().
INTEGER MPIParams::proc
Definition at line 139 of file common.f.
Referenced by main(), and Parameters().
INTEGER MPIParams::se
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::south
Definition at line 141 of file common.f.
Referenced by Init(), PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::sw
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER,parameter MPIParams::TAG1 = 1
Definition at line 145 of file common.f.
Referenced by Init(), PostCollision(), and PostStream().
INTEGER,parameter MPIParams::TAG2 = 2
Definition at line 145 of file common.f.
Referenced by Init(), PostCollision(), and PostStream().
INTEGER,parameter MPIParams::TAG3 = 3
Definition at line 145 of file common.f.
Referenced by PostCollision(), and PostStream().
INTEGER,parameter MPIParams::TAG4 = 4
Definition at line 145 of file common.f.
Referenced by PostCollision(), and PostStream().
INTEGER MPIParams::te
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::tn
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::top
Definition at line 141 of file common.f.
Referenced by Init(), PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::ts
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::tw
Definition at line 142 of file common.f.
Referenced by PostCollision(), PostStream(), and VGrid().
INTEGER MPIParams::vproc
Definition at line 139 of file common.f.
Referenced by filer(), FinalDump(), RelaxStats(), Stats(), and VGrid().
INTEGER MPIParams::west
Definition at line 141 of file common.f.
Referenced by Init(), PostCollision(), PostStream(), and VGrid().