ZSC-3D-STD-MPI: src/parallel/zsc-3d-src/vtkdump.f File Reference
src/parallel/zsc-3d-src/vtkdump.f File Reference
Detailed Description
Save order parameter, pressure, and velocity data in VTK format for the parallel D3Q7/D3Q19 Zheng-Shu-Chew multiphase LBM. Filenames are 'DATA_YYY_XXXXXXX.VTK' where YYY is the processor number and XXXXXXX is the time step. These files are understood by Paraview.
Definition in file vtkdump.f.
Functions/Subroutines
CHARACTER(12) filer ()
subroutine VtkDump
Function Documentation
CHARACTER(12) filer ()
Set vtk file name as a function of processor number and time step.
Definition at line 193 of file vtkdump.f.
References Domain::iStep, and MPIParams::vproc.
Referenced by VtkDump().
subroutine VtkDump ()
Definition at line 30 of file vtkdump.f.
References FluidParams::alpha, LBMParams::Cs_sq, filer(), LBMParams::g, Domain::inv12, Domain::inv6, FluidParams::kappa, MemAlloc(), Domain::ni, Domain::now, Domain::NPX, Domain::NPZ, FluidParams::phi, FluidParams::phiStar2, FluidParams::phiStar4, Domain::xjump, Domain::xl, Domain::xu, Domain::yl, Domain::yu, Domain::zl, and Domain::zu.
Referenced by Init(), and main().