ZSC-2D-STD-MPI: src/parallel/zsc-src/stats.f File Reference
src/parallel/zsc-src/stats.f File Reference
Detailed Description
Calculate average velocity, mass conservation factor, effective radius of the drop, pressure difference between the inside and the outside of the drop and the error with respect to the analytical value given by Laplace's equation, and write them to file "stats.out" for the parallel D2Q5/D2Q9 Zheng-Shu-Chew multiphase LBM.
The effective radius is calculated assuming the drop is a perfect circle with area given by A = Pi*R*R.
The pressure inside and the pressure outside of the drop are calculated as the average pressures inside and outside the drop, excluding the interface area.
Parallel implementation using MPI. Variables with the "Local" ending refer to quantities calculated locally in the current processor, vproc. Variables with the ending "Global" refer to qunatities calculated on the complete domain. The parameters stored in the MPI excahnge buffers are defined below.
Parameters:
data(1) : Volume
data(2) : Ux
data(3) : Uy
data(4) : Pin
data(5) : NodesIn
data(6) : Pout
data(7) : NodesOut
Definition in file stats.f.
Functions/Subroutines
subroutine Stats
Function Documentation
subroutine Stats ()
Definition at line 51 of file stats.f.
References FluidParams::bubbles, FluidParams::Convergence, FluidParams::eps, FluidParams::IntWidth, Domain::invInitVol, Domain::invPi, Domain::iStep, MPIParams::master, MemAlloc(), MPIParams::MPI_COMM_VGRID, FluidParams::p, FluidParams::phi, FluidParams::sigma, Domain::tCall, FluidParams::u, MPIParams::vproc, Domain::xl, Domain::xu, Domain::yl, and Domain::yu.
Referenced by Init(), and main().